services:
  # FE
  - type: web
    name: don-chameleone-fe
    branch: master
    runtime: static
    buildCommand: cd client; npm i; npm run build
    staticPublishPath: ./dist/client
    buildFilter:
      paths:
        - client/**/*
        - common/**/*
        - public/**/*
      ignoredPaths:
        - server/**/*
  # BE
  - type: web
    name: don-chameleone-be
    branch: master
    runtime: node
    buildCommand: cd server; npm i; npm run build
    startCommand: cd server; npm run start;
    buildFilter:
      paths:
        - server/**/*
        - common/**/*
        - public/**/*
      ignoredPaths:
        - client/**/*
